// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE5KKaUDK6eC2YeBBfod1lRvPmLN55CJs',
    appId: '1:3207424943:web:ed67580e173456c990dd5a',
    messagingSenderId: '3207424943',
    projectId: 'study-ai-app',
    authDomain: 'study-ai-app.firebaseapp.com',
    storageBucket: 'study-ai-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACWsfS1_vGVtMTxuSG1gnAyjOifQYtPY8',
    appId: '1:3207424943:android:4a60f0b773b5b5de90dd5a',
    messagingSenderId: '3207424943',
    projectId: 'study-ai-app',
    storageBucket: 'study-ai-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2hEIEAQvEJyWRG9h78b8cbiQ0mrvHZw8',
    appId: '1:3207424943:ios:3815dfc3232a90dc90dd5a',
    messagingSenderId: '3207424943',
    projectId: 'study-ai-app',
    storageBucket: 'study-ai-app.appspot.com',
    iosClientId: '3207424943-ji9lg2ld95nbac5uim67hm8cujrvga9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.intellistudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2hEIEAQvEJyWRG9h78b8cbiQ0mrvHZw8',
    appId: '1:3207424943:ios:3815dfc3232a90dc90dd5a',
    messagingSenderId: '3207424943',
    projectId: 'study-ai-app',
    storageBucket: 'study-ai-app.appspot.com',
    iosClientId: '3207424943-ji9lg2ld95nbac5uim67hm8cujrvga9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.intellistudy',
  );
}
